import Image from "next/image";
import { ICON_PATHS, DEFAULT_ICON_KEY } from "@/lib/icons";

/**
 * The artwork on a Tap Pad tile: a 3D object sitting directly on the tile's
 * own surface, generated by `scripts/generate-art.mjs`.
 *
 * It is a transparent cut-out rather than a filled badge, which is the whole
 * point — a badge is a second surface stacked on the tile, and six of them
 * turned the pad into a grid of stickers with the names underneath. The object
 * has no edge of its own, so the tile stays one surface and the name, the
 * amount and the tally marks read as part of the same object.
 *
 * That only works because the artwork is a single flat blue chosen to clear
 * both themes' surfaces (#4A78FF: 3.9:1 on white, 4.4:1 on #141C2C). With
 * nothing behind it, the art has to carry its own contrast — which is also why
 * there is one set of files rather than a light and a dark copy.
 */
export function TileArt({
  iconKey,
  size = 46,
  className = "",
}: {
  iconKey: string;
  size?: number;
  className?: string;
}) {
  // Unknown keys resolve the same way the stroked icon set resolves them, so a
  // tile from an older account or a server-side category still gets artwork.
  const key = iconKey in ICON_PATHS ? iconKey : DEFAULT_ICON_KEY;

  return (
    <Image
      src={`/art/tiles/${key}.webp`}
      alt=""
      width={size}
      height={size}
      // The pad is the first thing on the screen and every tile is above the
      // fold, so lazy-loading them only delays the paint that matters.
      priority
      /**
       * Served straight from `public`, not through the image optimizer.
       *
       * The source is already a 256px WebP of a few KB, drawn for a 46px box —
       * there is nothing left for the optimizer to win, and routing it through
       * `/_next/image` buys a per-URL disk cache that goes stale the moment the
       * art is regenerated. The filenames never change, so that cache keeps
       * serving the previous set until the server restarts, which is a
       * genuinely confusing thing to debug.
       */
      unoptimized
      draggable={false}
      className={className}
      style={{ display: "block", width: size, height: size }}
    />
  );
}

export default TileArt;
